### ISSUE TITLE
Bug: Longest word not reset or updated

### ISSUE THREAD

**Issue by DenB10** [akvedi/lexicon#22]
@akvedi

When you clear the history via the options page, the longest word is reset to "---" as expected in the popup.
However, if you remove the longest word from the personal dictionary, or if you remove the remaining word from the personal dictionary, the popup counter is updated, but the longest word is not.

P.S.
However, I would like to thank you warmly for all the significant improvements made since version 1.4.0. You now have an add-on that holds up formidably well.

@DenB10

**Comment by akvedi** [comment]
Appreciate your kind words 😀. All the improvement are solely due to your suggestions. So you deserve half of the credit. 

And about the longest word, In my opinion, it should refer to the longest word ever looked up rather than the longest word saved. and in this case it should be only removed when clearing the history.

**Comment by DenB10** [comment]
> And about the longest word, In my opinion, it should refer to the longest word ever looked up rather than the longest word saved. and in this case it should be only removed when clearing the history.

OK, that makes sense so no bugs, sorry for the inconvenience.
